<?php
$title = 'Ajouter une discussion';
$this->headTitle($title);
?>

<h1><?php echo $this->escape($title); ?></h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('discussion', array('action' => 'add')));
    echo $this->form()->openTag($form);
?>

<dl class="zend_form">
    <?php echo $this->formInput($form->get('id')); ?>
    <dt><?php echo $this->formLabel($form->get('title')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('title'));
        echo $this->formElementErrors($form->get('title'));
    ?></dd>
    <dd><?php
        echo $this->formInput($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
    ?></dd>
</dl>

<?php echo $this->form()->closeTag($form); ?>

