<?php
    $this->headLink()->appendStylesheet('/css/fam-icons.css');
?>
<div class="container">
    <h2>Accueil</h2>
    <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-cog"></i> Les Thèmes</a>
        </div>
        <div class="span9">
            Gestion des thèmes
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-page"></i> Les Discussions</a>
        </div>
        <div class="span9">
            Gestion des discussions
        </div>
    </div>
    <hr />
     <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-page"></i> Les Messages</a>
        </div>
        <div class="span9">
            Gestion des messages
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-user"></i> Utilisateurs</a>
        </div>
        <div class="span9">
            Gestion des utilisateurs
        </div>
    </div>
</div>