<?php
$title = 'Forum';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHTML($title); ?></h1>
<h3>Bienvenue sur le forum de league of Legends</h3>

<table class="table">
 <tr>
     <th>Les Themes</th>
     <th>Discussions</th>
     <th>date last message</th>
     <th>&nbsp;</th>
     
<?php foreach ($themes as $theme) { ?>
<tr>
	<td>
		<a href="<?php echo $this->url('discussion',array('idTheme'=> $theme->id))?>"> 
			<?php echo $theme->titre ?>
		</a>
	</td>
	<td>
		
	</td>
	<td>
		
	</td>		
</tr>
<?php } ?>
</table>




